# Generated by Django 5.2.17 on 2026-09-29 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('purpose', models.CharField(choices=[('backup', 'Respaldos'), ('monitoring', 'Monitoreo'), ('admin', 'Administracion'), ('api', 'API')], max_length=20)),
                ('auth_type', models.CharField(choices=[('ssh_password', 'SSH con password'), ('ssh_key', 'SSH con llave'), ('snmp_v2', 'SNMP v2'), ('snmp_v3', 'SNMP v3'), ('api_token', 'Token API'), ('other', 'Otro')], max_length=30)),
                ('storage_reference', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'perfil de credenciales',
                'verbose_name_plural': 'perfiles de credenciales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('hostname', models.CharField(blank=True, max_length=150)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=120, null=True)),
                ('asset_code', models.CharField(blank=True, max_length=80, null=True)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('access_point', 'Access point'), ('network_server', 'Servidor de red'), ('other', 'Otro')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('active', 'Activo'), ('maintenance', 'En mantenimiento'), ('retired', 'Retirado'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'dispositivo',
                'verbose_name_plural': 'dispositivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_family', models.CharField(blank=True, max_length=120)),
                ('device_type', models.CharField(choices=[('switch', 'Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('access_point', 'Access point'), ('network_server', 'Servidor de red'), ('other', 'Otro')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'modelo de dispositivo',
                'verbose_name_plural': 'modelos de dispositivo',
                'ordering': ['vendor__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'fabricante',
                'verbose_name_plural': 'fabricantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCredentialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('credential_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_assignments', to='inventory.credentialprofile')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_credential_profiles', to='inventory.device')),
            ],
            options={
                'verbose_name': 'perfil de credenciales por dispositivo',
                'verbose_name_plural': 'perfiles de credenciales por dispositivo',
                'ordering': ['device__name', 'credential_profile__name'],
            },
        ),
        migrations.AddField(
            model_name='credentialprofile',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='credential_profiles', through='inventory.DeviceCredentialProfile', to='inventory.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.devicemodel'),
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(choices=[('oxidized', 'Oxidized'), ('zabbix', 'Zabbix'), ('institutional_inventory', 'Inventario institucional'), ('other', 'Otro')], max_length=40)),
                ('external_id', models.CharField(max_length=150)),
                ('external_name', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='inventory.device')),
            ],
            options={
                'verbose_name': 'identificador externo',
                'verbose_name_plural': 'identificadores externos',
                'ordering': ['system', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_type', models.CharField(choices=[('oti', 'OTI'), ('faculty', 'Facultad'), ('office', 'Oficina'), ('laboratory', 'Laboratorio'), ('other', 'Otro')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.institutionalunit')),
            ],
            options={
                'verbose_name': 'unidad institucional',
                'verbose_name_plural': 'unidades institucionales',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.institutionalunit'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('campus', 'Sede'), ('building', 'Edificio'), ('floor', 'Piso'), ('room', 'Ambiente'), ('rack', 'Rack'), ('other', 'Otro')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.location')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventory.institutionalunit')),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['unit__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.vendor'),
        ),
        migrations.CreateModel(
            name='DeviceCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('ssh', 'SSH'), ('telnet', 'Telnet'), ('snmp', 'SNMP'), ('api', 'API'), ('oxidized_backup', 'Respaldo Oxidized'), ('zabbix_monitoring', 'Monitoreo Zabbix'), ('config_restore', 'Restauracion de configuracion'), ('interface_metrics', 'Metricas de interfaces'), ('other', 'Otro')], max_length=40)),
                ('status', models.CharField(choices=[('unknown', 'Desconocido'), ('supported', 'Soportado'), ('unsupported', 'No soportado'), ('pending_test', 'Pendiente de prueba')], default='unknown', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('detected', 'Detectado'), ('imported', 'Importado')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='inventory.device')),
            ],
            options={
                'verbose_name': 'capacidad de dispositivo',
                'verbose_name_plural': 'capacidades de dispositivo',
                'ordering': ['device__name', 'capability'],
                'indexes': [models.Index(fields=['capability', 'status'], name='inventory_d_capabil_a28278_idx'), models.Index(fields=['verified_at'], name='inventory_d_verifie_bc858b_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'capability'), name='inventory_device_capability_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='devicecredentialprofile',
            index=models.Index(fields=['is_active'], name='inventory_d_is_acti_e4d845_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicecredentialprofile',
            constraint=models.UniqueConstraint(fields=('device', 'credential_profile'), name='inventory_device_credential_profile_unique'),
        ),
        migrations.AddIndex(
            model_name='credentialprofile',
            index=models.Index(fields=['purpose', 'auth_type'], name='inventory_c_purpose_31250e_idx'),
        ),
        migrations.AddIndex(
            model_name='credentialprofile',
            index=models.Index(fields=['is_active'], name='inventory_c_is_acti_ffd47c_idx'),
        ),
        migrations.AddIndex(
            model_name='externalidentifier',
            index=models.Index(fields=['device', 'system'], name='inventory_e_device__026400_idx'),
        ),
        migrations.AddIndex(
            model_name='externalidentifier',
            index=models.Index(fields=['is_active'], name='inventory_e_is_acti_36d4ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalidentifier',
            constraint=models.UniqueConstraint(fields=('system', 'external_id'), name='inventory_external_system_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='externalidentifier',
            constraint=models.UniqueConstraint(fields=('device', 'system', 'external_id'), name='inventory_device_external_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='institutionalunit',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('code',), name='inventory_unit_code_unique_when_present'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['unit', 'location_type'], name='inventory_l_unit_id_ed917b_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_active'], name='inventory_l_is_acti_a5da3a_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['device_type'], name='inventory_d_device__47f4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['is_active'], name='inventory_d_is_acti_08509e_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'name'), name='inventory_device_model_vendor_name_unique'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['unit', 'status'], name='inventory_d_unit_id_7d2752_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['location'], name='inventory_d_locatio_c84604_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='inventory_d_device__82f1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['management_ip'], name='inventory_d_managem_27f23f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_demo'], name='inventory_d_is_demo_6631f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('management_ip__isnull', False)), fields=('management_ip',), name='inventory_device_management_ip_unique_when_present'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number__isnull', False)), fields=('serial_number',), name='inventory_device_serial_unique_when_present'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('asset_code__isnull', False)), fields=('asset_code',), name='inventory_device_asset_code_unique_when_present'),
        ),
    ]
